config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :deliveries do
  	  resources :reviews, except: [:show, :index]
  end
  
  get 'pages/about'

  get 'pages/contact'

  get 'pages/home'

  root 'deliveries#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
	mount_uploader :image, ImageUploader
	
	has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :delivery
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  before_action :set_delivery, only: [:show, :edit, :update, :destroy]

  # GET /deliveries
  # GET /deliveries.json
  def index
    @deliveries = Delivery.all
  end

  # GET /deliveries/1
  # GET /deliveries/1.json
  def show
    @reviews = Review.where(delivery_id: @delivery.id)
  end

  # GET /deliveries/new
  def new
    @delivery = Delivery.new
  end

  # GET /deliveries/1/edit
  def edit
  end

  # POST /deliveries
  # POST /deliveries.json
  def create
    @delivery = Delivery.new(delivery_params)

    respond_to do |format|
      if @delivery.save
        format.html { redirect_to @delivery, notice: 'Delivery was successfully created.' }
        format.json { render :show, status: :created, location: @delivery }
      else
        format.html { render :new }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deliveries/1
  # PATCH/PUT /deliveries/1.json
  def update
    respond_to do |format|
      if @delivery.update(delivery_params)
        format.html { redirect_to @delivery, notice: 'Delivery was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery }
      else
        format.html { render :edit }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deliveries/1
  # DELETE /deliveries/1.json
  def destroy
    @delivery.destroy
    respond_to do |format|
      format.html { redirect_to deliveries_url, notice: 'Delivery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery
      @delivery = Delivery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delivery_params
      params.require(:delivery).permit(:item, :address, :phone, :size, :time, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_delivery
  before_action :authenticate_user!
  # GET /reviews
  # GET /reviews.json

  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.delivery_id = @delivery.id
    respond_to do |format|
      if @review.save
        format.html { redirect_to delivery_path(@delivery), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_delivery
      @delivery = Delivery.find(params[:delivery_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		return '' if resource.errors.empty?

		messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
			sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count,
				resource: resource.class.model_name.human.downcase)

			html = <<-HTML
			<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
			<span class="sr-only">Close</span>
			</button>
			<h4>#{sentence}</h4>
			#{messages}
			</div>
			HTML

			html.html_safe
		end
	end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/deliveries/_form.html.erb
<%= form_for(@delivery, :html => { multipart: true }) do |f| %>
  <% if delivery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(delivery.errors.count, "error") %> prohibited this delivery from being saved:</h2>

      <ul>
      <% delivery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :item %>
    <%= f.text_field :item, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :size %>
    <%= f.text_field :size, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :time %>
    <%= f.text_field :time, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/deliveries/_form2.html.erb
<%= form2_for(@delivery, :html => { multipart: true }) do |f| %>
  <% if delivery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(delivery.errors.count, "error") %> prohibited this delivery from being saved:</h2>

      <ul>
      <% delivery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :item %>
    <%= f.text_field :item, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :size %>
    <%= f.text_field :size, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :time %>
    <%= f.text_field :time, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/deliveries/edit.html.erb
<h1>Editing Delivery</h1>

<%= render 'form', delivery: @delivery %>

<%= link_to 'Show', @delivery, class: "btn btn-link" %> |
<%= link_to 'Back', deliveries_path, class: "btn btn-link"  %>

app/views/deliveries/index.html.erb
<div class="jumbotron">
  <h1>NextPakk Go</h1>
  <p>The Smart, Secure, Convenient way for package delivery! "We've Got Your Pack"</p>
</div>
<h1>Deliveries</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Item</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Size</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deliveries.each do |delivery| %>
      <tr>
        <td><%= delivery.item %></td>
        <td><%= link_to delivery.address, "http://maps.google.com/?q=#{delivery.address}" %>          
        </td> 
        <td><%= delivery.phone %></td>
        <td><%= delivery.size %></td>
        <td><%= delivery.time %></td>
        <td><%= link_to 'Show', delivery, class: "btn btn-link"  %></td>
        <td><%= link_to 'Edit', edit_delivery_path(delivery), class: "btn btn-link"  %></td>
        <td><%= link_to 'Destroy', delivery, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delivery', new_delivery_path %>

app/views/deliveries/new.html.erb
<h1>New Delivery</h1>

<%= render 'form', delivery: @delivery %>

<%= link_to 'Back', deliveries_path, class: "btn btn-link"  %>

app/views/deliveries/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div id="imgZ" style="width: 300px; min-height: 240px; padding-bottom: 10px; border-radius: 60px !important;"><%= image_tag @delivery.image_url, class: "img-responsive img-circle" %>
    </div>
      <p>
        <h2><strong>Item:</strong>
        <%= @delivery.item %></h2>
      </p>

      <p>
        <strong>Address:</strong>
        <%= link_to @delivery.address, "http://maps.google.com/?q=#{@delivery.address}" %> 
      </p>

      <p>
        <strong>Phone:</strong>
        <%= @delivery.phone %>
      </p>

      <p>
        <strong>Size:</strong>
        <%= @delivery.size %>
      </p>

      <p>
        <strong>Time:</strong>
        <%= @delivery.time %>
      </p>

      <%= link_to "Write A Review", new_delivery_review_path(@delivery), class: "btn btn-primary" %>
    </div>
    <div class="col-md-8">
    <% if @reviews.blank? %>
        <h3>No reviews yet. Be the first to write one!</h3>
    <% else %>
        <% @reviews.each do |review| %>
        <p><%= review.rating %></p>
        <p><%= review.comment %></p>
      <% end %>
    <% end %>
    </div>
</div>
<%= link_to 'Edit', edit_delivery_path(@delivery), class: "btn btn-link"  %> |
<%= link_to 'Back', deliveries_path, class: "btn btn-link"  %>

app/views/layouts/_bootstrap.html.erb
  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JQuery -->
	<script src="http://code.jquery.com/jquery-3.1.1.slim.min.js"
	  integrity="sha256-/SIrNqv8h6QGKDuNoLGA4iret+kyesCkHGzVUUV0shc="
	  crossorigin="anonymous"></script>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<%= image_tag "https://s3.amazonaws.com/nextpakkweb/app-footer-image-web-app-1200w.jpg", class: "img-responsive" %>
<p>Copyright Lowell Fortune 2016</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "NextPakk", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
         <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nextpakkweb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= render '/layouts/bootstrap' %>
  <link href='http://fonts.googleapis.com/css?family=Days+One' rel='stylesheet'  type='text/css'>
</head>

  </head>
  <body>
  <%= render '/layouts/navbar' %>
    <div class="container-fluid">
    <% flash.each do |name, msg| %>
       <%if msg.is_a?(String) %>
          <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
          <% end %>
          <% end %>
    <%= yield %>
    <%= render '/layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>NextPakk</h1>
<p>NextPakk is not just a service. With the NextPakk app and our service, we have designed a system that brings package delivery into the 21st century.</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Reach out to us and let us know how we can help.</p>

app/views/pages/home.html.erb
<%= image_tag "https://s3.amazonaws.com/nextpakkweb/app-header-image-web-app-1200w.jpg", class: "img-responsive" %>
<div class="row">
	<div class="col-md-6">
		<h1>Smart, Secure, <br />Convenient!</h1>
		<h4>"We've Got Your Pack"</h4>
		<h3>Problems We Solve:</h3>

		<p>->Never miss a delivery <br />
		->Avoid stolen packages <br />
		->Protect deliveries from weather<br /> 
		->Track your packages with the NextPakk app<br /> 
		->Pick-up Service for return shipments </p>
	</div>
	<div class="col-md-6">
		<h1>Form goes here!</h1>
	</div>


</div>

app/views/reviews/_form.html.erb
<%= form_for([@delivery, @review]) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :rating %>
    <%= f.number_field :rating, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', delivery_path(@delivery), class: "btn btn-link"  %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', '#', class: "btn btn-link"  %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_review_path(@review), class: "btn btn-link"  %> |
<%= link_to 'Back', reviews_path, class: "btn btn-link"  %>